source 'http://rubygems.org'

gem 'github-pages'
gem 'rake'
gem 'rouge'
gem 'pygments.rb'
gem 'jekyll'
gem 'html-proofer'
gem 'jemoji'
gem 'jekyll-admin',:git => 'git@github.com:jekyll/jekyll-admin.git'
gem 'jekyll-mentions'
gem 'jekyll-seo-tag'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-gist'

